ip:
  name: MCFP
  version: v1
  clock_mhz: 650
  ports:
    - name: CIN0
      kind: cin
      direction: in
    - name: COUT0
      kind: cout
      direction: out
  dmas:
    - name: RDMA_REF
      direction: read
      type: image
      bus_width_byte: 32
      max_outstanding: 8
      fifo_depth: 16
      xiu_port: XIU2
      ppc: 2
      hint: LLC_ALLOC
      support_sbwc: true
      pattern: raster
    - name: WDMA_OUT
      direction: write
      type: image
      bind: COUT0
      bus_width_byte: 32
      max_outstanding: 8
      fifo_depth: 16
      xiu_port: XIU3
      ppc: 2
      hint: PARTIAL_ALLOC
      support_sbwc: true
      pattern: tile_2d
      tile_width: 64
      tile_height: 32
