from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path
from typing import Any

from dma_traffic_gen.core.transaction import Transaction
from dma_traffic_gen.output.summary import ScenarioSummary


class BWGraphGenerator:
    def __init__(self, transactions: list[Transaction], summary: ScenarioSummary, window_us: int = 10) -> None:
        self.transactions = transactions
        self.summary = summary
        self.window_us = window_us

    def generate(self, output_path: str) -> None:
        try:
            import plotly.graph_objects as go  # type: ignore
            import plotly.io as pio  # type: ignore

            series = self._calc_bw_timeseries()
            figs = [
                ("DMA Bandwidth Over Time (Read+Write)", self._build_dma_bw_chart(go, series, direction_filter=None)),
                ("DMA Bandwidth Over Time (Read)", self._build_dma_bw_chart(go, series, direction_filter="read")),
                ("DMA Bandwidth Over Time (Write)", self._build_dma_bw_chart(go, series, direction_filter="write")),
                ("XIU Port Aggregate Bandwidth (Read+Write)", self._build_xiu_bw_chart(go, series, direction_filter=None)),
                ("XIU Port Aggregate Bandwidth (Read)", self._build_xiu_bw_chart(go, series, direction_filter="read")),
                ("XIU Port Aggregate Bandwidth (Write)", self._build_xiu_bw_chart(go, series, direction_filter="write")),
                ("Transaction Density Heatmap", self._build_density_heatmap(go, series)),
            ]
            sections = []
            for idx, (title, fig) in enumerate(figs):
                fig_html = pio.to_html(
                    fig,
                    full_html=False,
                    include_plotlyjs=True if idx == 0 else False,
                    config={"responsive": True, "displaylogo": False},
                )
                sections.append(f'<section class="card"><h2>{title}</h2>{fig_html}</section>')
            sections.insert(6, self._build_bw_summary_table_section(series))

            topology_mermaid = self._build_topology_mermaid()
            topology_html = ""
            if topology_mermaid:
                topology_html = f'''<section class="card">
  <h2>Topology Graph</h2>
  <div class="mermaid">
{topology_mermaid}
  </div>
</section>'''

            html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{self.summary.data["scenario"]} BW Plot</title>
  <script type="module">
    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
    mermaid.initialize({{ startOnLoad: true }});
  </script>
  <style>
    body {{ margin: 0; padding: 24px; background: #eef3f8; color: #13233a; font-family: Segoe UI, sans-serif; }}
    h1 {{ margin: 0 0 16px 0; }}
    .meta {{ margin: 0 0 24px 0; color: #49627e; }}
    .card {{ background: #fff; border-radius: 14px; padding: 18px; margin-bottom: 18px; box-shadow: 0 10px 30px rgba(19,35,58,0.08); }}
    .plotly-graph-div {{ width: 100% !important; }}
    table {{ width: 100%; border-collapse: collapse; font-size: 14px; }}
    th, td {{ border-bottom: 1px solid #d7e1ee; padding: 10px 8px; text-align: right; }}
    th:first-child, td:first-child {{ text-align: left; }}
    thead th {{ background: #f4f7fb; color: #27405c; position: sticky; top: 0; }}
    .row-ip td {{ color: #164a7b; font-weight: 700; background: #f7fbff; }}
    .row-dma td {{ color: #7b4f16; }}
    .row-dma td:first-child {{ padding-left: 28px; }}
  </style>
</head>
<body>
  <h1>{self.summary.data["scenario"]}</h1>
  <p class="meta">Standalone bandwidth report generated by dma_traffic_gen.</p>
  {topology_html}
  {''.join(sections)}
</body>
</html>
"""
            Path(output_path).write_text(html, encoding="utf-8")
            return
        except Exception:
            pass

        series = self._calc_bw_timeseries()
        payload = json.dumps({"summary": self.summary.data, "series": series}, ensure_ascii=False)
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>BW Plot</title>
  <style>
    body {{ font-family: Segoe UI, sans-serif; margin: 24px; background: #f7f9fc; color: #13233a; }}
    .card {{ background: white; border-radius: 14px; padding: 16px; margin-bottom: 16px; box-shadow: 0 8px 24px rgba(0,0,0,0.08); }}
    pre {{ white-space: pre-wrap; }}
  </style>
</head>
<body>
  <h1>{self.summary.data["scenario"]}</h1>
  <div class="card"><h2>Graph 1: DMA BW</h2><pre id="dma-bw"></pre></div>
  <div class="card"><h2>Graph 2: XIU BW</h2><pre id="xiu-bw"></pre></div>
  <div class="card"><h2>Graph 3: Avg / Peak BW</h2><pre id="avg-peak"></pre></div>
  <div class="card"><h2>Graph 4: Density</h2><pre id="density"></pre></div>
  <script>
    const payload = {payload};
    document.getElementById("dma-bw").textContent = Object.entries(payload.series.by_port)
      .map(([port, rows]) => `${{port}} peak=${{Math.max(...rows.map(r => r.bw_gbps), 0).toFixed(3)}} samples=${{rows.length}}`)
      .join("\\n");
    document.getElementById("xiu-bw").textContent = Object.entries(payload.series.by_xiu)
      .map(([xiu, rows]) => `${{xiu}} peak=${{Math.max(...rows.map(r => r.bw_gbps), 0).toFixed(3)}} samples=${{rows.length}}`)
      .join("\\n");
    document.getElementById("avg-peak").textContent = payload.summary.dma_summary
      .map(item => `${{item.port}} avg=${{item.avg_bw_gbps}} peak=${{item.peak_bw_gbps}}`)
      .join("\\n");
    document.getElementById("density").textContent = Object.entries(payload.series.density)
      .map(([port, windows]) => `${{port}} windows=${{Object.keys(windows).length}}`)
      .join("\\n");
  </script>
</body>
</html>
"""
        Path(output_path).write_text(html, encoding="utf-8")

    def _build_topology_mermaid(self) -> str:
        links = self.summary.data.get("links", [])
        if not links:
            return ""
        
        lines = ["flowchart LR"]
        for link in links:
            from_ip = link["from"].split(".")[0]
            to_ip = link["to"].split(".")[0]
            link_type = link["type"].upper()
            
            if link.get("sw_task"):
                delay_ms = round(link.get("delay_ns", 0.0) / 1_000_000.0, 2)
                task_name = link["sw_task"]
                node_id = f"SW_{task_name}"
                lines.append(f"    {from_ip} -->|{link_type}| {node_id}[\"{task_name}<br/>({delay_ms}ms)\"]")
                lines.append(f"    {node_id} -->|{link_type}| {to_ip}")
            else:
                lines.append(f"    {from_ip} -->|{link_type}| {to_ip}")
        
        return "\n".join(lines)

    def _calc_bw_timeseries(self) -> dict[str, Any]:
        requested_window_ns = max(1, self.window_us) * 1_000.0
        if self.transactions:
            min_ts = min(txn.ts_ns for txn in self.transactions)
            max_ts = max(txn.ts_ns for txn in self.transactions)
            span_ns = max(0.001, max_ts - min_ts)
            adaptive_window_ns = max(0.001, span_ns / 50)
            window_ns = min(requested_window_ns, adaptive_window_ns) if span_ns < requested_window_ns * 4 else requested_window_ns
        else:
            window_ns = requested_window_ns
        by_port_bytes: dict[str, dict[int, int]] = defaultdict(dict)
        by_xiu_bytes: dict[str, dict[int, int]] = defaultdict(dict)
        by_xiu_read_bytes: dict[str, dict[int, int]] = defaultdict(dict)
        by_xiu_write_bytes: dict[str, dict[int, int]] = defaultdict(dict)
        density: dict[str, dict[int, int]] = defaultdict(dict)
        xiu_map = {item["port"]: item["xiu"] for item in self.summary.data.get("dma_summary", [])}
        direction_map = {item["port"]: item["direction"] for item in self.summary.data.get("dma_summary", [])}

        for txn in self.transactions:
            window_idx = int(txn.ts_ns // window_ns)
            port_bucket = by_port_bytes[txn.port]
            port_bucket[window_idx] = port_bucket.get(window_idx, 0) + txn.size_byte
            density[txn.port][window_idx] = density[txn.port].get(window_idx, 0) + 1
            xiu = xiu_map.get(txn.port, "UNKNOWN")
            xiu_bucket = by_xiu_bytes[xiu]
            xiu_bucket[window_idx] = xiu_bucket.get(window_idx, 0) + txn.size_byte
            direction = direction_map.get(txn.port, "read")
            if direction == "read":
                xiu_read_bucket = by_xiu_read_bytes[xiu]
                xiu_read_bucket[window_idx] = xiu_read_bucket.get(window_idx, 0) + txn.size_byte
            else:
                xiu_write_bucket = by_xiu_write_bytes[xiu]
                xiu_write_bucket[window_idx] = xiu_write_bucket.get(window_idx, 0) + txn.size_byte

        def to_rows(source: dict[str, dict[int, int]]) -> dict[str, list[dict[str, float]]]:
            return {
                name: [
                    {
                        "time_ms": round((window_idx * window_ns) / 1_000_000, 6),
                        "bw_gbps": round(total_byte / window_ns, 6),
                    }
                    for window_idx, total_byte in sorted(windows.items())
                ]
                for name, windows in source.items()
            }

        return {
            "by_port": to_rows(by_port_bytes),
            "by_xiu": to_rows(by_xiu_bytes),
            "by_xiu_read": to_rows(by_xiu_read_bytes),
            "by_xiu_write": to_rows(by_xiu_write_bytes),
            "density": density,
            "window_ns": window_ns,
        }

    def _port_direction(self, port: str) -> str:
        for item in self.summary.data.get("dma_summary", []):
            if item["port"] == port:
                return item["direction"]
        return "read"

    def _build_dma_bw_chart(self, go, series: dict[str, Any], direction_filter: str | None):
        fig = go.Figure()
        for port, rows in series["by_port"].items():
            direction = self._port_direction(port)
            if direction_filter and direction != direction_filter:
                continue
            rows = self._series_with_terminal_zero(rows, series["window_ns"])
            fig.add_trace(
                go.Scatter(
                    x=[r["time_ms"] for r in rows],
                    y=[r["bw_gbps"] for r in rows],
                    mode="lines",
                    name=port,
                    line={"dash": "solid" if direction == "read" else "dot"},
                    hovertemplate="port=%{fullData.name}<br>time=%{x:.6f} ms<br>bw=%{y:.4f} GB/s<extra></extra>",
                )
            )
        fig.update_layout(template="plotly_white", height=420, legend={"orientation": "h"})
        end_time_ms = round(float(self.summary.data.get("duration_ms", 0.0)), 6)
        fig.update_xaxes(title_text="Time (ms)", range=[0, end_time_ms] if end_time_ms > 0 else None)
        fig.update_yaxes(title_text="BW (GB/s)")
        return fig

    def _build_xiu_bw_chart(self, go, series: dict[str, Any], direction_filter: str | None):
        fig = go.Figure()
        if direction_filter == "read":
            source = series["by_xiu_read"]
        elif direction_filter == "write":
            source = series["by_xiu_write"]
        else:
            source = series["by_xiu"]
        for xiu, rows in source.items():
            rows = self._series_with_terminal_zero(rows, series["window_ns"])
            fig.add_trace(
                go.Scatter(
                    x=[r["time_ms"] for r in rows],
                    y=[r["bw_gbps"] for r in rows],
                    mode="lines",
                    stackgroup="xiu",
                    name=xiu,
                    hovertemplate="xiu=%{fullData.name}<br>time=%{x:.6f} ms<br>bw=%{y:.4f} GB/s<extra></extra>",
                )
            )
        fig.update_layout(template="plotly_white", height=420, legend={"orientation": "h"})
        end_time_ms = round(float(self.summary.data.get("duration_ms", 0.0)), 6)
        fig.update_xaxes(title_text="Time (ms)", range=[0, end_time_ms] if end_time_ms > 0 else None)
        fig.update_yaxes(title_text="BW (GB/s)")
        return fig

    def _build_density_heatmap(self, go, series: dict[str, Any]):
        density_ports = list(series["density"].keys())
        density_x = sorted({int(window_idx) for windows in series["density"].values() for window_idx in windows.keys()})
        density_z = [
            [series["density"][port].get(window_idx, 0) for window_idx in density_x]
            for port in density_ports
        ]
        density_time_ms = [round((window_idx * series["window_ns"]) / 1_000_000, 6) for window_idx in density_x]
        fig = go.Figure()
        if density_ports and density_time_ms:
            fig.add_trace(
                go.Heatmap(
                    z=density_z,
                    x=density_time_ms,
                    y=density_ports,
                    colorscale="Blues",
                    colorbar={"title": "Txn count"},
                    hovertemplate="port=%{y}<br>time=%{x:.6f} ms<br>count=%{z}<extra></extra>",
                )
            )
        fig.update_layout(template="plotly_white", height=500)
        end_time_ms = round(float(self.summary.data.get("duration_ms", 0.0)), 6)
        fig.update_xaxes(title_text="Time (ms)", range=[0, end_time_ms])
        fig.update_yaxes(title_text="DMA")
        return fig

    def _series_with_terminal_zero(self, rows: list[dict[str, float]], window_ns: float) -> list[dict[str, float]]:
        if not rows:
            return rows
        result = [dict(row) for row in rows]
        end_time_ms = round(self.summary.data.get("duration_ms", rows[-1]["time_ms"]), 6)
        window_ms = round(window_ns / 1_000_000, 6)
        if result[0]["time_ms"] > 0:
            first_ms = result[0]["time_ms"]
            if first_ms > window_ms:
                result.insert(0, {"time_ms": round(first_ms - window_ms, 6), "bw_gbps": 0.0})
            result.insert(0, {"time_ms": 0.0, "bw_gbps": 0.0})
        terminal_ms = result[-1]["time_ms"] + max(window_ms, 0.000001)
        if end_time_ms > result[-1]["time_ms"]:
            terminal_ms = min(terminal_ms, end_time_ms)
        terminal_ms = round(terminal_ms, 6)
        if terminal_ms <= result[-1]["time_ms"]:
            terminal_ms = round(result[-1]["time_ms"] + max(window_ms, 0.000001), 6)
        result.append({"time_ms": terminal_ms, "bw_gbps": 0.0})
        return result

    def _build_bw_summary_table_section(self, series: dict[str, Any]) -> str:
        metrics = self._build_bw_summary_metrics(series)
        header = """
<section class="card">
  <h2>Average / Peak Bandwidth Table</h2>
  <table>
    <thead>
      <tr>
        <th>Target</th>
        <th>Avg BW (R+W)</th>
        <th>Avg BW (R)</th>
        <th>Avg BW (W)</th>
        <th>Peak BW (R+W)</th>
        <th>Peak BW (R)</th>
        <th>Peak BW (W)</th>
      </tr>
    </thead>
    <tbody>
"""
        rows: list[str] = []
        for ip_name in sorted(metrics["ip"].keys()):
            rows.append(self._table_row(ip_name, metrics["ip"][ip_name], row_class="row-ip"))
            for port in sorted(metrics["dma_by_ip"][ip_name].keys()):
                rows.append(self._table_row(port, metrics["dma_by_ip"][ip_name][port], row_class="row-dma"))
        footer = """
    </tbody>
  </table>
</section>
"""
        return header + "".join(rows) + footer

    def _table_row(self, label: str, values: dict[str, float], row_class: str) -> str:
        return (
            f'<tr class="{row_class}">'
            f"<td>{label}</td>"
            f"<td>{values['avg_total']:.3f}</td>"
            f"<td>{values['avg_read']:.3f}</td>"
            f"<td>{values['avg_write']:.3f}</td>"
            f"<td>{values['peak_total']:.3f}</td>"
            f"<td>{values['peak_read']:.3f}</td>"
            f"<td>{values['peak_write']:.3f}</td>"
            "</tr>"
        )

    def _build_bw_summary_metrics(self, series: dict[str, Any]) -> dict[str, Any]:
        duration_ns = max(float(self.summary.data.get("duration_ns", 0.0)), 0.001)
        dma_items = self.summary.data.get("dma_summary", [])
        ip_map: dict[str, list[dict[str, Any]]] = defaultdict(list)
        for item in dma_items:
            ip_map[item.get("ip", "UNKNOWN_IP")].append(item)

        def peak_from_windows(windows: dict[int, int], window_ns: float) -> float:
            peak_bytes = max(windows.values(), default=0)
            return peak_bytes / window_ns if window_ns else 0.0

        window_ns = series["window_ns"]
        dma_by_ip: dict[str, dict[str, dict[str, float]]] = defaultdict(dict)
        ip_metrics: dict[str, dict[str, float]] = {}

        for item in dma_items:
            direction = item["direction"]
            avg_total = float(item["avg_bw_gbps"])
            peak_total = float(item["peak_bw_gbps"])
            dma_by_ip[item.get("ip", "UNKNOWN_IP")][item["port"]] = {
                "avg_total": avg_total,
                "avg_read": avg_total if direction == "read" else 0.0,
                "avg_write": avg_total if direction == "write" else 0.0,
                "peak_total": peak_total,
                "peak_read": peak_total if direction == "read" else 0.0,
                "peak_write": peak_total if direction == "write" else 0.0,
            }

        for ip_name, items in ip_map.items():
            total_bytes = 0
            read_bytes = 0
            write_bytes = 0
            total_windows: dict[int, int] = defaultdict(int)
            read_windows: dict[int, int] = defaultdict(int)
            write_windows: dict[int, int] = defaultdict(int)
            ports = {item["port"] for item in items}

            for txn in self.transactions:
                if txn.port not in ports:
                    continue
                total_bytes += txn.size_byte
                window_idx = int(txn.ts_ns // window_ns)
                total_windows[window_idx] += txn.size_byte
                if txn.txn_type == "Read":
                    read_bytes += txn.size_byte
                    read_windows[window_idx] += txn.size_byte
                else:
                    write_bytes += txn.size_byte
                    write_windows[window_idx] += txn.size_byte

            ip_metrics[ip_name] = {
                "avg_total": total_bytes / duration_ns,
                "avg_read": read_bytes / duration_ns,
                "avg_write": write_bytes / duration_ns,
                "peak_total": peak_from_windows(total_windows, window_ns),
                "peak_read": peak_from_windows(read_windows, window_ns),
                "peak_write": peak_from_windows(write_windows, window_ns),
            }

        return {"ip": ip_metrics, "dma_by_ip": dma_by_ip}
